// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyvtqhWK39WlJ2soCStU0aThsbFbNkWSY',
    appId: '1:404648324583:web:85b7912eeabbfb4eada142',
    messagingSenderId: '404648324583',
    projectId: 'jocar97',
    authDomain: 'jocar97.firebaseapp.com',
    storageBucket: 'jocar97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIknGif_rXb4FuB5peOReSwKFXNhl3pc',
    appId: '1:404648324583:android:0058e13fd6188dcaada142',
    messagingSenderId: '404648324583',
    projectId: 'jocar97',
    storageBucket: 'jocar97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusMu6Q8v4EkkPawaLVrBVVWtxR4r5L8E',
    appId: '1:404648324583:ios:054e50399f4fd95fada142',
    messagingSenderId: '404648324583',
    projectId: 'jocar97',
    storageBucket: 'jocar97.appspot.com',
    iosClientId:
        '404648324583-n3q19il4f4ad8cf55riaecr1k4hcbeo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.joCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDusMu6Q8v4EkkPawaLVrBVVWtxR4r5L8E',
    appId: '1:404648324583:ios:054e50399f4fd95fada142',
    messagingSenderId: '404648324583',
    projectId: 'jocar97',
    storageBucket: 'jocar97.appspot.com',
    iosClientId:
        '404648324583-n3q19il4f4ad8cf55riaecr1k4hcbeo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.joCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyvtqhWK39WlJ2soCStU0aThsbFbNkWSY',
    appId: '1:404648324583:web:19602d79ca3ec852ada142',
    messagingSenderId: '404648324583',
    projectId: 'jocar97',
    authDomain: 'jocar97.firebaseapp.com',
    storageBucket: 'jocar97.appspot.com',
  );
}
